type ROUTES_TYPE = {
  MAIN_TAB: 'MAIN_TAB';
  HOME: 'HOME';
  LOGIN: 'LOGIN';
  LIST_USER: 'LIST_USER';
  USER_DETAIL: 'USER_DETAIL';
  NOTI_DATE: 'NOTI_DATE';
  NOTI_MONEY_TODAY: 'NOTI_MONEY_TODAY';
};

export const ROUTES: ROUTES_TYPE = {
  MAIN_TAB: 'MAIN_TAB',
  HOME: 'HOME',
  LOGIN: 'LOGIN',
  LIST_USER: 'LIST_USER',
  USER_DETAIL: 'USER_DETAIL',
  NOTI_DATE: 'NOTI_DATE',
  NOTI_MONEY_TODAY: 'NOTI_MONEY_TODAY',
};
